name: sast scanning

on:
  push:
  pull_request:

jobs:
  checkov_scanning:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    
    - name: Run checkov
      run: |
        docker run --rm -t \
        -v "$(pwd):/terraform" \
        bridgecrew/checkov \
        --quiet \
        --compact \
        --directory /terraform \
        --output junitxml \
        --soft-fail > checkov.xml

  tfsec_scanning:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Run tfsec
      run: |
        docker run --rm -t \
        -v "$(pwd):/src" \
        aquasec/tfsec \
        --format junit
        /src > tfsec.xml
    
  upload_sast:
    needs: [tfsec_scanning, checkov_scanning]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: upload testresults
      uses: actions/upload-artifact@master
      with:
        name: sast
        path: ./*.xml
        if-no-files-found: error